apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: jira-clone
type: Opaque
data:
  # sam9311
  root-password: c2FtOTMxMQ==
  # jiraclone
  database: amlyYWNsb25l

---

apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: jira-clone
type: Opaque
data:
  # admin
  admin-password: YWRtaW4=

---

apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: jira-clone
type: Opaque
data:
  # sam9311
  db-password: c2FtOTMxMQ==
  # change-me-before-registering-webhook  (base64 of your actual secret)
  webhook-secret: Y2hhbmdlLW1lLWJlZm9yZS1yZWdpc3RlcmluZy13ZWJob29r
