apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jira-clone-ingress
  namespace: jira-clone
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: jira-clone.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: jira-clone-backend
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jira-clone-frontend
                port:
                  number: 80
    - host: auth.jira-clone.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
